package com.hectorfortuna.fonoBack.FonoBackend.mapper;

import com.hectorfortuna.fonoBack.FonoBackend.dto.evaluation.*;
import com.hectorfortuna.fonoBack.FonoBackend.model.evaluation.*;
import com.hectorfortuna.fonoBack.FonoBackend.model.patient.Patient;
import com.hectorfortuna.fonoBack.FonoBackend.model.patientevaluation.PatientEvaluation;
import org.springframework.stereotype.Component;

@Component
public class EvaluationMapper {
    public EvaluationDTO convertToDTO(Evaluation entity) {
        return EvaluationDTO.builder()
                .id(entity.getId())
                .patientId(entity.getPatientEvaluation() != null ? entity.getPatientEvaluation().getPatient().getId() : null)
                .gestation(convertToGestationDTO(entity.getGestation()))
                .nutrition(convertToNutritionDTO(entity.getNutrition()))
                .sleep(convertToSleepDTO(entity.getSleep()))
                .psychomotorDevelopment(convertToPsychomotorDevelopmentDTO(entity.getPsychomotorDevelopment()))
                .languageDevelopment(convertToLanguageDevelopmentDTO(entity.getLanguageDevelopment()))
                .pathologicalHistory(convertToPathologicalHistoryDTO(entity.getPathologicalHistory()))
                .independenceAndComprehension(convertToIndependenceAndComprehensionDTO(entity.getIndependenceAndComprehension()))
                .habitsAndTics(convertToHabitsAndTicsDTO(entity.getHabitsAndTics()))
                .schooling(convertToSchoolingDTO(entity.getSchooling()))
                .recreation(convertToRecreationDTO(entity.getRecreation()))
                .familyInterrelationship(convertToFamilyInterrelationshipDTO(entity.getFamilyInterrelationship()))
                .mainComplaint(entity.getMainComplaint())
                .evaluationData(entity.getEvaluationData())
                .build();
    }


    public Evaluation convertToEntity(EvaluationDTO dto, Patient patient) {
        Evaluation evaluation = Evaluation.builder()
                .gestation(convertToGestation(dto.getGestation()))
                .nutrition(convertToNutrition(dto.getNutrition()))
                .sleep(convertToSleep(dto.getSleep()))
                .psychomotorDevelopment(convertToPsychomotorDevelopment(dto.getPsychomotorDevelopment()))
                .languageDevelopment(convertToLanguageDevelopment(dto.getLanguageDevelopment()))
                .pathologicalHistory(convertToPathologicalHistory(dto.getPathologicalHistory()))
                .independenceAndComprehension(convertToIndependenceAndComprehension(dto.getIndependenceAndComprehension()))
                .habitsAndTics(convertToHabitsAndTics(dto.getHabitsAndTics()))
                .schooling(convertToSchooling(dto.getSchooling()))
                .recreation(convertToRecreation(dto.getRecreation()))
                .familyInterrelationship(convertToFamilyInterrelationship(dto.getFamilyInterrelationship()))
                .mainComplaint(dto.getMainComplaint())
                .evaluationData(dto.getEvaluationData())
                .build();

        PatientEvaluation patientEvaluation = PatientEvaluation.builder()
                .patient(patient)
                .evaluation(evaluation)
                .build();

        evaluation.setPatientEvaluation(patientEvaluation);

        return evaluation;
    }

    public Recreation convertToRecreation(RecreationDTO dto) {
        return Recreation.builder()
                .favoriteActivitiesAndToys(dto.getFavoriteActivitiesAndToys())
                .adaptsHasFriends(dto.getAdaptsHasFriends())
                .favoriteBooksAndTvShows(dto.getFavoriteBooksAndTvShows())
                .observations(dto.getObservations())
                .playsWithObjects(dto.getPlaysWithObjects())
                .typicalExploration(dto.getTypicalExploration())
                .atypicalExploration(dto.getAtypicalExploration())
                .functionalPlay(dto.getFunctionalPlay())
                .symbolicPlayWithMiniatures(dto.getSymbolicPlayWithMiniatures())
                .symbolicPlayWithObjects(dto.getSymbolicPlayWithObjects())
                .symbolicPlayWithRoles(dto.getSymbolicPlayWithRoles())
                .operateConsistently(dto.getOperateConsistently())
                .pretendPlayMiniatures(dto.getPretendPlayMiniatures())
                .pretendPlayObjects(dto.getPretendPlayObjects())
                .pretendPlayRoles(dto.getPretendPlayRoles())
                .build();
    }

     public FamilyInterrelationship convertToFamilyInterrelationship(FamilyInterrelationshipDTO dto) {
        return FamilyInterrelationship.builder()
                .relationshipFather(dto.getRelationshipFather())
                .relationshipMother(dto.getRelationshipMother())
                .relationshipSiblings(dto.getRelationshipSiblings())
                .relationshipOthers(dto.getRelationshipOthers())
                .headOrientationToAdult(dto.getHeadOrientationToAdult())
                .smilesAtFamiliarPeople(dto.getSmilesAtFamiliarPeople())
                .smilesAtUnfamiliarPeople(dto.getSmilesAtUnfamiliarPeople())
                .smilesInResponse(dto.getSmilesInResponse())
                .facialExpressionVariation(dto.getFacialExpressionVariation())
                .emotionalExpressionContext(dto.getEmotionalExpressionContext())
                .isAffectionate(dto.getIsAffectionate())
                .sharesPleasure(dto.getSharesPleasure())
                .caresAboutParents(dto.getCaresAboutParents())
                .jointAttentionPointing(dto.getJointAttentionPointing())
                .commentsGesturesOrSpeech(dto.getCommentsGesturesOrSpeech())
                .followsPointing(dto.getFollowsPointing())
                .respondsToPlayInvitation(dto.getRespondsToPlayInvitation())
                .initiatesWithChildren(dto.getInitiatesWithChildren())
                .respondsButNoInitiative(dto.getRespondsButNoInitiative())
                .anxiousWithChildren(dto.getAnxiousWithChildren())
                .stereotypedPlayOnly(dto.getStereotypedPlayOnly())
                .prefersPairPlay(dto.getPrefersPairPlay())
                .anxiousWithStrangers(dto.getAnxiousWithStrangers())
                .avoidsStrangerContact(dto.getAvoidsStrangerContact())
                .persistentAggression(dto.getPersistentAggression())
                .excessiveDisinhibition(dto.getExcessiveDisinhibition())
                .contextualBehaviorVariation(dto.getContextualBehaviorVariation())
                .worriesWhenApart(dto.getWorriesWhenApart())
                .smilesAtParentsReturn(dto.getSmilesAtParentsReturn())
                .asksParentsForHelp(dto.getAsksParentsForHelp())
                .checksParentsInNewPlaces(dto.getChecksParentsInNewPlaces())
                .schoolAdaptation(dto.getSchoolAdaptation())
                .observations(dto.getObservations())
                .build();
    }
     public Gestation convertToGestation(GestationDTO dto) {
        return Gestation.builder()
                .gestationDuration(dto.getGestationDuration())
                .motherAge(dto.getMotherAge())
                .prenatalTreatment(dto.getPrenatalTreatment())
                .accidents(dto.getAccidents())
                .diseasesDuringPregnancy(dto.getDiseasesDuringPregnancy())
                .medicationsDuringPregnancy(dto.getMedicationsDuringPregnancy())
                .hypotension(dto.getHypotension())
                .hypertension(dto.getHypertension())
                .anemia(dto.getAnemia())
                .deliveryDuration(dto.getDeliveryDuration())
                .normalDelivery(dto.getNormalDelivery())
                .forcepsDelivery(dto.getForcepsDelivery())
                .cesareanDelivery(dto.getCesareanDelivery())
                .anesthesia(dto.getAnesthesia())
                .birthWeight(dto.getBirthWeight())
                .birthHeight(dto.getBirthHeight())
                .cried(dto.getCried())
                .cyanosis(dto.getCyanosis())
                .pregnancyExperience(dto.getPregnancyExperience())
                .coupleRelationship(dto.getCoupleRelationship())
                .maternalHealthConditions(dto.getMaternalHealthConditions())
                .postpartumExperience(dto.getPostpartumExperience())
                .motherBabyHealthPostpartum(dto.getMotherBabyHealthPostpartum())
                .postpartumDepression(dto.getPostpartumDepression())
                .firstDaysAtHome(dto.getFirstDaysAtHome())
                .observations(dto.getObservations())
                .build();
    }

     public Nutrition convertToNutrition(NutritionDTO dto) {
        return Nutrition.builder()
                .breastfeeding(dto.getBreastfeeding())
                .breastfeedingDuration(dto.getBreastfeedingDuration())
                .artificialFeeding(dto.getArtificialFeeding())
                .artificialFeedingDuration(dto.getArtificialFeedingDuration())
                .goodSuctionSwallowing(dto.getGoodSuctionSwallowing())
                .choking(dto.getChoking())
                .vomiting(dto.getVomiting())
                .forcedEat(dto.getForcedEat())
                .currentFeeding(dto.getCurrentFeeding())
                .weaning(dto.getWeaning())
                .bottleFeedingAge(dto.getBottleFeedingAge())
                .solidFoodIntroductionAge(dto.getSolidFoodIntroductionAge())
                .acceptsDifferentTextures(dto.getAcceptsDifferentTextures())
                .feedingIssuesDescription(dto.getFeedingIssuesDescription())
                .foodSelectivity(dto.getFoodSelectivity())
                .observations(dto.getObservations())
                .build();
    }

     public Sleep convertToSleep(SleepDTO dto) {
        return Sleep.builder()
                .normal(dto.getNormal())
                .restless(dto.getRestless())
                .talksDuringSleep(dto.getTalksDuringSleep())
                .nocturnalEnuresis(dto.getNocturnalEnuresis())
                .teethGrinding(dto.getTeethGrinding())
                .sleepwalking(dto.getSleepwalking())
                .sleepsWithMouthOpen(dto.getSleepsWithMouthOpen())
                .drools(dto.getDrools())
                .asBabyNoProblems(dto.getAsBabyNoProblems())
                .asBabySleptAlone(dto.getAsBabySleptAlone())
                .asBabySharedWith(dto.getAsBabySharedWith())
                .asBabySleepDifficulties(dto.getAsBabySleepDifficulties())
                .currentNoProblems(dto.getCurrentNoProblems())
                .currentSleptAlone(dto.getCurrentSleptAlone())
                .currentSharedWith(dto.getCurrentSharedWith())
                .currentSleepDifficulties(dto.getCurrentSleepDifficulties())
                .observations(dto.getObservations())
                .build();
    }

     public PsychomotorDevelopment convertToPsychomotorDevelopment(PsychomotorDevelopmentDTO dto) {
        return PsychomotorDevelopment.builder()
                .heldHeadUp(dto.getHeldHeadUp())
                .crawled(dto.getCrawled())
                .crawledAge(dto.getCrawledAge())
                .walkedAge(dto.getWalkedAge())
                .floppyOrFirmBaby(dto.getFloppyOrFirmBaby())
                .fallingFrequency(dto.getFallingFrequency())
                .grabbedObjectsAge(dto.getGrabbedObjectsAge())
                .canJump(dto.getCanJump())
                .walkingDefects(dto.getWalkingDefects())
                .goodDirectionSense(dto.getGoodDirectionSense())
                .sphincterControl(dto.getSphincterControl())
                .bumpsIntoThings(dto.getBumpsIntoThings())
                .dropsThingsFromHands(dto.getDropsThingsFromHands())
                .agile(dto.getAgile())
                .orthopedicProblems(dto.getOrthopedicProblems())
                .usedBoots(dto.getUsedBoots())
                .dailyActivities(dto.getDailyActivities())
                .walksOnTiptoes(dto.getWalksOnTiptoes())
                .swingsWhenWalking(dto.getSwingsWhenWalking())
                .hasBalanceIssues(dto.getHasBalanceIssues())
                .difficultyRunningClimbing(dto.getDifficultyRunningClimbing())
                .postureProblems(dto.getPostureProblems())
                .difficultyWithObjects(dto.getDifficultyWithObjects())
                .difficultyPlaying(dto.getDifficultyPlaying())
                .motorExamples(dto.getMotorExamples())
                .bathAlone(dto.getBathAlone())
                .brushesTeethAlone(dto.getBrushesTeethAlone())
                .cleansSelf(dto.getCleansSelf())
                .difficultyWithHygieneSequence(dto.getDifficultyWithHygieneSequence())
                .dressesSelf(dto.getDressesSelf())
                .buttonsClothes(dto.getButtonsClothes())
                .tiesShoes(dto.getTiesShoes())
                .observations(dto.getObservations())
                .build();
    }

     public LanguageDevelopment convertToLanguageDevelopment(LanguageDevelopmentDTO dto) {
        return LanguageDevelopment.builder()
                .babbled(dto.getBabbled())
                .syllableRepetition(dto.getSyllableRepetition())
                .wordsWithMeaning(dto.getWordsWithMeaning())
                .simpleCompleteSentences(dto.getSimpleCompleteSentences())
                .understoodByAllWhen(dto.getUnderstoodByAllWhen())
                .stutteredAround(dto.getStutteredAround())
                .understandCommands(dto.getUnderstandCommands())
                .emitsPrimitiveSounds(dto.getEmitsPrimitiveSounds())
                .languageUnderstood(dto.getLanguageUnderstood())
                .usesGesture(dto.getUsesGesture())
                .sings(dto.getSings())
                .knowsSongs(dto.getKnowsSongs())
                .observations(dto.getObservations())
                .firstVocalizationsAge(dto.getFirstVocalizationsAge())
                .firstWords(dto.getFirstWords())
                .firstSentences(dto.getFirstSentences())
                .speechDelay(dto.getSpeechDelay())
                .gestureHelp(dto.getGestureHelp())
                .gestureShare(dto.getGestureShare())
                .gestureNodYes(dto.getGestureNodYes())
                .gestureNodNo(dto.getGestureNodNo())
                .gestureWave(dto.getGestureWave())
                .gestureBlowKiss(dto.getGestureBlowKiss())
                .gestureImitate(dto.getGestureImitate())
                .gestureClap(dto.getGestureClap())
                .gestureLiftArms(dto.getGestureLiftArms())
                .gestureShakeFingerNo(dto.getGestureShakeFingerNo())
                .looksWhenPointed(dto.getLooksWhenPointed())
                .usesAdultHand(dto.getUsesAdultHand())
                .answersToName(dto.getAnswersToName())
                .speechArticulation(dto.getSpeechArticulation())
                .speechRhythm(dto.getSpeechRhythm())
                .echolalia(dto.getEcholalia())
                .repeatsPhrases(dto.getRepeatsPhrases())
                .pronounConfusion(dto.getPronounConfusion())
                .inventsWords(dto.getInventsWords())
                .strangeWordCombinations(dto.getStrangeWordCombinations())
                .insistsOnRepetition(dto.getInsistsOnRepetition())
                .reactionWhenContradicted(dto.getReactionWhenContradicted())
                .build();
    }

     public PathologicalHistory convertToPathologicalHistory(PathologicalHistoryDTO dto) {
        return PathologicalHistory.builder()
                .physicalMalformations(dto.getPhysicalMalformations())
                .measles(dto.getMeasles())
                .smallpox(dto.getSmallpox())
                .highFever(dto.getHighFever())
                .fallsBlows(dto.getFallsBlows())
                .psychosomaticDisorders(dto.getPsychosomaticDisorders())
                .tonsilsAdenoids(dto.getTonsilsAdenoids())
                .operationsDone(dto.getOperationsDone())
                .seesWell(dto.getSeesWell())
                .wearsGlasses(dto.getWearsGlasses())
                .optometristReason(dto.getOptometristReason())
                .optometristResult(dto.getOptometristResult())
                .hearingProblems(dto.getHearingProblems())
                .whichEar(dto.getWhichEar())
                .howUnderstands(dto.getHowUnderstands())
                .attendTherapy(dto.getAttendTherapy())
                .familyDevelopmentHistory(dto.getFamilyDevelopmentHistory())
                .familySurgeriesHospitalizations(dto.getFamilySurgeriesHospitalizations())
                .observations(dto.getObservations())
                .build();
    }

     public IndependenceAndComprehension convertToIndependenceAndComprehension(IndependenceAndComprehensionDTO dto) {
        return IndependenceAndComprehension.builder()
                .startedEatingAloneAge(dto.getStartedEatingAloneAge())
                .startedDressingAloneAge(dto.getStartedDressingAloneAge())
                .startedBathingAloneAge(dto.getStartedBathingAloneAge())
                .startedIdentifyingObjectsAge(dto.getStartedIdentifyingObjectsAge())
                .observations(dto.getObservations())
                .build();
    }

     public HabitsAndTics convertToHabitsAndTics(HabitsAndTicsDTO dto) {
        return HabitsAndTics.builder()
                .usedPacifier(dto.getUsedPacifier())
                .pacifierRemovalMethod(dto.getPacifierRemovalMethod())
                .suckedThumb(dto.getSuckedThumb())
                .thumbHand(dto.getThumbHand())
                .thumbSuckingDuration(dto.getThumbSuckingDuration())
                .thumbSuckingRemovalMethod(dto.getThumbSuckingRemovalMethod())
                .bitesNails(dto.getBitesNails())
                .nailBitingHand(dto.getNailBitingHand())
                .alignsObjects(dto.getAlignsObjects())
                .playsWithPartsOnly(dto.getPlaysWithPartsOnly())
                .opensAndClosesObjects(dto.getOpensAndClosesObjects())
                .reactionWhenPlayInterrupted(dto.getReactionWhenPlayInterrupted())
                .rigidPretendPlay(dto.getRigidPretendPlay())
                .resistsRoutineChange(dto.getResistsRoutineChange())
                .fixedActivitySequence(dto.getFixedActivitySequence())
                .reactionToInterruption(dto.getReactionToInterruption())
                .attachedToUnusualObjects(dto.getAttachedToUnusualObjects())
                .handNearFace(dto.getHandNearFace())
                .handsNearBody(dto.getHandsNearBody())
                .bodySwing(dto.getBodySwing())
                .armFlapping(dto.getArmFlapping())
                .fears(dto.getFears())
                .sensoryInterest(dto.getSensoryInterest())
                .soundSensitivity(dto.getSoundSensitivity())
                .inappropriateTouch(dto.getInappropriateTouch())
                .hyperactivity(dto.getHyperactivity())
                .observations(dto.getObservations())
                .build();
    }

     public Schooling convertToSchooling(SchoolingDTO dto) {
        return Schooling.builder()
                .doesWellInSchool(dto.getDoesWellInSchool())
                .likesToStudy(dto.getLikesToStudy())
                .parentsStudyWithChild(dto.getParentsStudyWithChild())
                .arithmeticDifficulties(dto.getArithmeticDifficulties())
                .writingDifficulties(dto.getWritingDifficulties())
                .hasBeenHeldBack(dto.getHasBeenHeldBack())
                .reasonForBeingHeldBack(dto.getReasonForBeingHeldBack())
                .attendedKindergarten(dto.getAttendedKindergarten())
                .kindergartenAge(dto.getKindergartenAge())
                .changedSchoolsOften(dto.getChangedSchoolsOften())
                .currentGrade(dto.getCurrentGrade())
                .currentSchool(dto.getCurrentSchool())
                .observations(dto.getObservations())
                .build();
    }

    private GestationDTO convertToGestationDTO(Gestation entity) {
        return GestationDTO.builder()
                .gestationDuration(entity.getGestationDuration())
                .motherAge(entity.getMotherAge())
                .prenatalTreatment(entity.getPrenatalTreatment())
                .accidents(entity.getAccidents())
                .diseasesDuringPregnancy(entity.getDiseasesDuringPregnancy())
                .medicationsDuringPregnancy(entity.getMedicationsDuringPregnancy())
                .hypotension(entity.getHypotension())
                .hypertension(entity.getHypertension())
                .anemia(entity.getAnemia())
                .deliveryDuration(entity.getDeliveryDuration())
                .normalDelivery(entity.getNormalDelivery())
                .forcepsDelivery(entity.getForcepsDelivery())
                .cesareanDelivery(entity.getCesareanDelivery())
                .anesthesia(entity.getAnesthesia())
                .birthWeight(entity.getBirthWeight())
                .birthHeight(entity.getBirthHeight())
                .cried(entity.getCried())
                .cyanosis(entity.getCyanosis())
                .observations(entity.getObservations())
                .pregnancyExperience(entity.getPregnancyExperience())
                .coupleRelationship(entity.getCoupleRelationship())
                .maternalHealthConditions(entity.getMaternalHealthConditions())
                .postpartumExperience(entity.getPostpartumExperience())
                .motherBabyHealthPostpartum(entity.getMotherBabyHealthPostpartum())
                .postpartumDepression(entity.getPostpartumDepression())
                .firstDaysAtHome(entity.getFirstDaysAtHome())
                .build();
    }

    private NutritionDTO convertToNutritionDTO(Nutrition entity) {
        return NutritionDTO.builder()
                .breastfeeding(entity.getBreastfeeding())
                .breastfeedingDuration(entity.getBreastfeedingDuration())
                .artificialFeeding(entity.getArtificialFeeding())
                .artificialFeedingDuration(entity.getArtificialFeedingDuration())
                .goodSuctionSwallowing(entity.getGoodSuctionSwallowing())
                .choking(entity.getChoking())
                .vomiting(entity.getVomiting())
                .forcedEat(entity.getForcedEat())
                .currentFeeding(entity.getCurrentFeeding())
                .weaning(entity.getWeaning())
                .bottleFeedingAge(entity.getBottleFeedingAge())
                .solidFoodIntroductionAge(entity.getSolidFoodIntroductionAge())
                .acceptsDifferentTextures(entity.getAcceptsDifferentTextures())
                .feedingIssuesDescription(entity.getFeedingIssuesDescription())
                .foodSelectivity(entity.getFoodSelectivity())
                .observations(entity.getObservations())
                .build();
    }

    private SleepDTO convertToSleepDTO(Sleep entity) {
        return SleepDTO.builder()
                .normal(entity.getNormal())
                .restless(entity.getRestless())
                .talksDuringSleep(entity.getTalksDuringSleep())
                .nocturnalEnuresis(entity.getNocturnalEnuresis())
                .teethGrinding(entity.getTeethGrinding())
                .sleepwalking(entity.getSleepwalking())
                .sleepsWithMouthOpen(entity.getSleepsWithMouthOpen())
                .drools(entity.getDrools())
                .asBabyNoProblems(entity.getAsBabyNoProblems())
                .asBabySleptAlone(entity.getAsBabySleptAlone())
                .asBabySharedWith(entity.getAsBabySharedWith())
                .asBabySleepDifficulties(entity.getAsBabySleepDifficulties())
                .currentNoProblems(entity.getCurrentNoProblems())
                .currentSleptAlone(entity.getCurrentSleptAlone())
                .currentSharedWith(entity.getCurrentSharedWith())
                .currentSleepDifficulties(entity.getCurrentSleepDifficulties())
                .observations(entity.getObservations())
                .build();
    }

    private PsychomotorDevelopmentDTO convertToPsychomotorDevelopmentDTO(PsychomotorDevelopment entity) {
        return PsychomotorDevelopmentDTO.builder()
                .heldHeadUp(entity.getHeldHeadUp())
                .crawled(entity.getCrawled())
                .crawledAge(entity.getCrawledAge())
                .walkedAge(entity.getWalkedAge())
                .floppyOrFirmBaby(entity.getFloppyOrFirmBaby())
                .fallingFrequency(entity.getFallingFrequency())
                .grabbedObjectsAge(entity.getGrabbedObjectsAge())
                .canJump(entity.getCanJump())
                .walkingDefects(entity.getWalkingDefects())
                .goodDirectionSense(entity.getGoodDirectionSense())
                .sphincterControl(entity.getSphincterControl())
                .bumpsIntoThings(entity.getBumpsIntoThings())
                .dropsThingsFromHands(entity.getDropsThingsFromHands())
                .agile(entity.getAgile())
                .orthopedicProblems(entity.getOrthopedicProblems())
                .usedBoots(entity.getUsedBoots())
                .dailyActivities(entity.getDailyActivities())
                .walksOnTiptoes(entity.getWalksOnTiptoes())
                .swingsWhenWalking(entity.getSwingsWhenWalking())
                .hasBalanceIssues(entity.getHasBalanceIssues())
                .difficultyRunningClimbing(entity.getDifficultyRunningClimbing())
                .postureProblems(entity.getPostureProblems())
                .difficultyWithObjects(entity.getDifficultyWithObjects())
                .difficultyPlaying(entity.getDifficultyPlaying())
                .motorExamples(entity.getMotorExamples())
                .bathAlone(entity.getBathAlone())
                .brushesTeethAlone(entity.getBrushesTeethAlone())
                .cleansSelf(entity.getCleansSelf())
                .difficultyWithHygieneSequence(entity.getDifficultyWithHygieneSequence())
                .dressesSelf(entity.getDressesSelf())
                .buttonsClothes(entity.getButtonsClothes())
                .tiesShoes(entity.getTiesShoes())
                .observations(entity.getObservations())
                .build();
    }

    private LanguageDevelopmentDTO convertToLanguageDevelopmentDTO(LanguageDevelopment entity) {
        return LanguageDevelopmentDTO.builder()
                .babbled(entity.getBabbled())
                .syllableRepetition(entity.getSyllableRepetition())
                .wordsWithMeaning(entity.getWordsWithMeaning())
                .simpleCompleteSentences(entity.getSimpleCompleteSentences())
                .understoodByAllWhen(entity.getUnderstoodByAllWhen())
                .stutteredAround(entity.getStutteredAround())
                .understandCommands(entity.getUnderstandCommands())
                .emitsPrimitiveSounds(entity.getEmitsPrimitiveSounds())
                .languageUnderstood(entity.getLanguageUnderstood())
                .usesGesture(entity.getUsesGesture())
                .sings(entity.getSings())
                .knowsSongs(entity.getKnowsSongs())
                .observations(entity.getObservations())
                .firstVocalizationsAge(entity.getFirstVocalizationsAge())
                .firstWords(entity.getFirstWords())
                .firstSentences(entity.getFirstSentences())
                .speechDelay(entity.getSpeechDelay())
                .gestureHelp(entity.getGestureHelp())
                .gestureShare(entity.getGestureShare())
                .gestureNodYes(entity.getGestureNodYes())
                .gestureNodNo(entity.getGestureNodNo())
                .gestureWave(entity.getGestureWave())
                .gestureBlowKiss(entity.getGestureBlowKiss())
                .gestureImitate(entity.getGestureImitate())
                .gestureClap(entity.getGestureClap())
                .gestureLiftArms(entity.getGestureLiftArms())
                .gestureShakeFingerNo(entity.getGestureShakeFingerNo())
                .looksWhenPointed(entity.getLooksWhenPointed())
                .usesAdultHand(entity.getUsesAdultHand())
                .answersToName(entity.getAnswersToName())
                .speechArticulation(entity.getSpeechArticulation())
                .speechRhythm(entity.getSpeechRhythm())
                .echolalia(entity.getEcholalia())
                .repeatsPhrases(entity.getRepeatsPhrases())
                .pronounConfusion(entity.getPronounConfusion())
                .inventsWords(entity.getInventsWords())
                .strangeWordCombinations(entity.getStrangeWordCombinations())
                .insistsOnRepetition(entity.getInsistsOnRepetition())
                .reactionWhenContradicted(entity.getReactionWhenContradicted())
                .build();
    }
    private PathologicalHistoryDTO convertToPathologicalHistoryDTO(PathologicalHistory entity) {
        return PathologicalHistoryDTO.builder()
                .physicalMalformations(entity.getPhysicalMalformations())
                .measles(entity.getMeasles())
                .smallpox(entity.getSmallpox())
                .highFever(entity.getHighFever())
                .fallsBlows(entity.getFallsBlows())
                .psychosomaticDisorders(entity.getPsychosomaticDisorders())
                .tonsilsAdenoids(entity.getTonsilsAdenoids())
                .operationsDone(entity.getOperationsDone())
                .seesWell(entity.getSeesWell())
                .wearsGlasses(entity.getWearsGlasses())
                .optometristReason(entity.getOptometristReason())
                .optometristResult(entity.getOptometristResult())
                .hearingProblems(entity.getHearingProblems())
                .whichEar(entity.getWhichEar())
                .howUnderstands(entity.getHowUnderstands())
                .attendTherapy(entity.getAttendTherapy())
                .familyDevelopmentHistory(entity.getFamilyDevelopmentHistory())
                .familySurgeriesHospitalizations(entity.getFamilySurgeriesHospitalizations())
                .observations(entity.getObservations())
                .build();
    }

    private IndependenceAndComprehensionDTO convertToIndependenceAndComprehensionDTO(IndependenceAndComprehension entity) {
        return IndependenceAndComprehensionDTO.builder()
                .startedEatingAloneAge(entity.getStartedEatingAloneAge())
                .startedDressingAloneAge(entity.getStartedDressingAloneAge())
                .startedBathingAloneAge(entity.getStartedBathingAloneAge())
                .startedIdentifyingObjectsAge(entity.getStartedIdentifyingObjectsAge())
                .observations(entity.getObservations())
                .build();
    }

    private HabitsAndTicsDTO convertToHabitsAndTicsDTO(HabitsAndTics entity) {
        return HabitsAndTicsDTO.builder()
                .usedPacifier(entity.getUsedPacifier())
                .pacifierRemovalMethod(entity.getPacifierRemovalMethod())
                .suckedThumb(entity.getSuckedThumb())
                .thumbHand(entity.getThumbHand())
                .thumbSuckingDuration(entity.getThumbSuckingDuration())
                .thumbSuckingRemovalMethod(entity.getThumbSuckingRemovalMethod())
                .bitesNails(entity.getBitesNails())
                .nailBitingHand(entity.getNailBitingHand())
                .alignsObjects(entity.getAlignsObjects())
                .playsWithPartsOnly(entity.getPlaysWithPartsOnly())
                .opensAndClosesObjects(entity.getOpensAndClosesObjects())
                .reactionWhenPlayInterrupted(entity.getReactionWhenPlayInterrupted())
                .rigidPretendPlay(entity.getRigidPretendPlay())
                .resistsRoutineChange(entity.getResistsRoutineChange())
                .fixedActivitySequence(entity.getFixedActivitySequence())
                .reactionToInterruption(entity.getReactionToInterruption())
                .attachedToUnusualObjects(entity.getAttachedToUnusualObjects())
                .handNearFace(entity.getHandNearFace())
                .handsNearBody(entity.getHandsNearBody())
                .bodySwing(entity.getBodySwing())
                .armFlapping(entity.getArmFlapping())
                .fears(entity.getFears())
                .sensoryInterest(entity.getSensoryInterest())
                .soundSensitivity(entity.getSoundSensitivity())
                .inappropriateTouch(entity.getInappropriateTouch())
                .hyperactivity(entity.getHyperactivity())
                .observations(entity.getObservations())
                .build();
    }

    private SchoolingDTO convertToSchoolingDTO(Schooling entity) {
        return SchoolingDTO.builder()
                .doesWellInSchool(entity.getDoesWellInSchool())
                .likesToStudy(entity.getLikesToStudy())
                .parentsStudyWithChild(entity.getParentsStudyWithChild())
                .arithmeticDifficulties(entity.getArithmeticDifficulties())
                .writingDifficulties(entity.getWritingDifficulties())
                .hasBeenHeldBack(entity.getHasBeenHeldBack())
                .reasonForBeingHeldBack(entity.getReasonForBeingHeldBack())
                .attendedKindergarten(entity.getAttendedKindergarten())
                .kindergartenAge(entity.getKindergartenAge())
                .changedSchoolsOften(entity.getChangedSchoolsOften())
                .currentGrade(entity.getCurrentGrade())
                .currentSchool(entity.getCurrentSchool())
                .observations(entity.getObservations())
                .build();
    }

    private RecreationDTO convertToRecreationDTO(Recreation entity) {
        return RecreationDTO.builder()
                .favoriteActivitiesAndToys(entity.getFavoriteActivitiesAndToys())
                .adaptsHasFriends(entity.getAdaptsHasFriends())
                .favoriteBooksAndTvShows(entity.getFavoriteBooksAndTvShows())
                .playsWithObjects(entity.getPlaysWithObjects())
                .typicalExploration(entity.getTypicalExploration())
                .atypicalExploration(entity.getAtypicalExploration())
                .functionalPlay(entity.getFunctionalPlay())
                .symbolicPlayWithMiniatures(entity.getSymbolicPlayWithMiniatures())
                .symbolicPlayWithObjects(entity.getSymbolicPlayWithObjects())
                .symbolicPlayWithRoles(entity.getSymbolicPlayWithRoles())
                .operateConsistently(entity.getOperateConsistently())
                .pretendPlayMiniatures(entity.getPretendPlayMiniatures())
                .pretendPlayObjects(entity.getPretendPlayObjects())
                .pretendPlayRoles(entity.getPretendPlayRoles())
                .observations(entity.getObservations())
                .build();
    }

    private FamilyInterrelationshipDTO convertToFamilyInterrelationshipDTO(FamilyInterrelationship entity) {
        return FamilyInterrelationshipDTO.builder()
                .relationshipFather(entity.getRelationshipFather())
                .relationshipMother(entity.getRelationshipMother())
                .relationshipSiblings(entity.getRelationshipSiblings())
                .relationshipOthers(entity.getRelationshipOthers())
                .headOrientationToAdult(entity.getHeadOrientationToAdult())
                .smilesAtFamiliarPeople(entity.getSmilesAtFamiliarPeople())
                .smilesAtUnfamiliarPeople(entity.getSmilesAtUnfamiliarPeople())
                .smilesInResponse(entity.getSmilesInResponse())
                .facialExpressionVariation(entity.getFacialExpressionVariation())
                .emotionalExpressionContext(entity.getEmotionalExpressionContext())
                .isAffectionate(entity.getIsAffectionate())
                .sharesPleasure(entity.getSharesPleasure())
                .caresAboutParents(entity.getCaresAboutParents())
                .jointAttentionPointing(entity.getJointAttentionPointing())
                .commentsGesturesOrSpeech(entity.getCommentsGesturesOrSpeech())
                .followsPointing(entity.getFollowsPointing())
                .respondsToPlayInvitation(entity.getRespondsToPlayInvitation())
                .initiatesWithChildren(entity.getInitiatesWithChildren())
                .respondsButNoInitiative(entity.getRespondsButNoInitiative())
                .anxiousWithChildren(entity.getAnxiousWithChildren())
                .stereotypedPlayOnly(entity.getStereotypedPlayOnly())
                .prefersPairPlay(entity.getPrefersPairPlay())
                .anxiousWithStrangers(entity.getAnxiousWithStrangers())
                .avoidsStrangerContact(entity.getAvoidsStrangerContact())
                .persistentAggression(entity.getPersistentAggression())
                .excessiveDisinhibition(entity.getExcessiveDisinhibition())
                .contextualBehaviorVariation(entity.getContextualBehaviorVariation())
                .worriesWhenApart(entity.getWorriesWhenApart())
                .smilesAtParentsReturn(entity.getSmilesAtParentsReturn())
                .asksParentsForHelp(entity.getAsksParentsForHelp())
                .checksParentsInNewPlaces(entity.getChecksParentsInNewPlaces())
                .schoolAdaptation(entity.getSchoolAdaptation())
                .observations(entity.getObservations())
                .build();
    }

}
