spring:
  application:
    name: FonoBackend

  datasource:
    url: jdbc:postgresql://fono-db.cb4isgooqm7u.us-east-2.rds.amazonaws.com:5432/fono_db
    username: master
    password: Newqac-simjuf-mybvi4
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.hectorfortuna.fonoBack: DEBUG
